//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APQC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APQC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días.
        /// </summary>
        internal static string DIAS {
            get {
                return ResourceManager.GetString("DIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importando métricas.
        /// </summary>
        internal static string IMPORT_METRICS {
            get {
                return ResourceManager.GetString("IMPORT_METRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importando procesos.
        /// </summary>
        internal static string IMPORT_PROCESSES {
            get {
                return ResourceManager.GetString("IMPORT_PROCESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de APQC - EA.
        /// </summary>
        internal static string ITEM_MENU__ACERCA_DE {
            get {
                return ResourceManager.GetString("ITEM_MENU__ACERCA_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        internal static string ITEM_MENU__IMPORTAR {
            get {
                return ResourceManager.GetString("ITEM_MENU__IMPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando planilla.
        /// </summary>
        internal static string LOADING_SHEET {
            get {
                return ResourceManager.GetString("LOADING_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando opciones de tradución.
        /// </summary>
        internal static string LOADING_TRANSLATE_OPTIONS {
            get {
                return ResourceManager.GetString("LOADING_TRANSLATE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando métricas desde el modelo.
        /// </summary>
        internal static string MESSAGE_LOAD_METRICS {
            get {
                return ResourceManager.GetString("MESSAGE_LOAD_METRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se importan métricas.
        /// </summary>
        internal static string NO_IMPORT_METRICS {
            get {
                return ResourceManager.GetString("NO_IMPORT_METRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se importan procesos.
        /// </summary>
        internal static string NO_IMPORT_PROCESSES {
            get {
                return ResourceManager.GetString("NO_IMPORT_PROCESSES", resourceCulture);
            }
        }
    }
}
