///////////////////////////////////////////////////////////
//  Basic.cs
//  Implementation of the Class Basic
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:29
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Basic : SecurityScheme {

	public Basic(){

	}

	~Basic(){

	}

}//end Basic