///////////////////////////////////////////////////////////
//  ParameterInBody.cs
//  Implementation of the Class ParameterInBody
//  Generated by Enterprise Architect
//  Created on:      30-jul.-2017 12:20:57
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace RestFul.modelo
 {
	public class ParameterInBody{

        public JsonSchema schema = new JsonSchema();

		public ParameterInBody(){

		}
	}
}