//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar el paquete que contiene los paquetes con los lenguajes.
        /// </summary>
        public static string DEBE_SELECCIONAR_PAQUETE_LENGUAJE {
            get {
                return ResourceManager.GetString("DEBE_SELECCIONAR_PAQUETE_LENGUAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluando artefacto.
        /// </summary>
        public static string FRK_ARTIFACT_EVALUATING {
            get {
                return ResourceManager.GetString("FRK_ARTIFACT_EVALUATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando artefactos.
        /// </summary>
        public static string FRK_ARTIFACT_LOADING {
            get {
                return ResourceManager.GetString("FRK_ARTIFACT_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando templates desde valores etiquetados.
        /// </summary>
        public static string FRK_ARTIFACT_LOADING_TEMPLATE_FROM_TV {
            get {
                return ResourceManager.GetString("FRK_ARTIFACT_LOADING_TEMPLATE_FROM_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando las plantillas.
        /// </summary>
        public static string FRK_ARTIFACT_LOADING_TEMPLATES {
            get {
                return ResourceManager.GetString("FRK_ARTIFACT_LOADING_TEMPLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El artefacto {0} no se genera.
        /// </summary>
        public static string FRK_ARTIFACT_SKIP {
            get {
                return ResourceManager.GetString("FRK_ARTIFACT_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agregó el json definido para el dialecto.
        /// </summary>
        public static string FRK_DATA_DLC_AGREGADO {
            get {
                return ResourceManager.GetString("FRK_DATA_DLC_AGREGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agregó el json definido para el lenguaje.
        /// </summary>
        public static string FRK_DATA_LNG_AGREGADO {
            get {
                return ResourceManager.GetString("FRK_DATA_LNG_AGREGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al intentar generar el artefacto.
        /// </summary>
        public static string FRK_GENERATION_ERROR {
            get {
                return ResourceManager.GetString("FRK_GENERATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha generado el artefacto.
        /// </summary>
        public static string FRK_GENERATION_OK {
            get {
                return ResourceManager.GetString("FRK_GENERATION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha guardado el archivo.
        /// </summary>
        public static string FRK_GENERATION_SAVE {
            get {
                return ResourceManager.GetString("FRK_GENERATION_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando heplers para HandleBars.
        /// </summary>
        public static string FRK_HANDLEBARS_HELPER_AGREGADO {
            get {
                return ResourceManager.GetString("FRK_HANDLEBARS_HELPER_AGREGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando funciones de JavaScript.
        /// </summary>
        public static string FRK_JS_FUNCTION_AGREGADO {
            get {
                return ResourceManager.GetString("FRK_JS_FUNCTION_AGREGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando helper de handlebars.
        /// </summary>
        public static string FRK_SETTING_JSE_HB_HELPERS {
            get {
                return ResourceManager.GetString("FRK_SETTING_JSE_HB_HELPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando template de handlebars.
        /// </summary>
        public static string FRK_SETTING_JSE_HB_TEMPLATE {
            get {
                return ResourceManager.GetString("FRK_SETTING_JSE_HB_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han cargado las funciones de js.
        /// </summary>
        public static string FRK_SETTING_JSE_JS_FUNCTIONS {
            get {
                return ResourceManager.GetString("FRK_SETTING_JSE_JS_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando JSon del artefacto.
        /// </summary>
        public static string FRK_SETTING_JSE_JSON_ARTIFACT {
            get {
                return ResourceManager.GetString("FRK_SETTING_JSE_JSON_ARTIFACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando la plantilla principal al motor de js.
        /// </summary>
        public static string FRK_SETTING_JSE_MAIN_TEMPLATE {
            get {
                return ResourceManager.GetString("FRK_SETTING_JSE_MAIN_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string GUARDAR_EN_DISCO_TITLE {
            get {
                return ResourceManager.GetString("GUARDAR_EN_DISCO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string GUARDAR_TITLE {
            get {
                return ResourceManager.GetString("GUARDAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el guid del framework.
        /// </summary>
        public static string NO_HAY_GUID_FRAMEWORK {
            get {
                return ResourceManager.GetString("NO_HAY_GUID_FRAMEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si elige &quot;No&quot;, el contenido estará disponible en el portapapeles.
        /// </summary>
        public static string OPCIONES_GENERACION_TITLE {
            get {
                return ResourceManager.GetString("OPCIONES_GENERACION_TITLE", resourceCulture);
            }
        }
    }
}
