///////////////////////////////////////////////////////////
//  Tag.cs
//  Implementation of the Class Tag
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 14:00:03
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Una lista de etiquetas utilizadas por la especificación con metadatos
/// adicionales. El orden de las etiquetas se puede utilizar para reflejar en su
/// orden por las herramientas de análisis. No se deben declarar todas las
/// etiquetas utilizadas por el objeto Operación. Las etiquetas que no se declaran
/// pueden organizarse aleatoriamente o basarse en la lógica de las herramientas.
/// Cada nombre de etiqueta en la lista DEBE ser único.
/// </summary>
public class Tag {

	public Tag(){

	}

	~Tag(){

	}

}//end Tag