//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18N.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18N.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        internal static string DIAS {
            get {
                return ResourceManager.GetString("DIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulte el mensaje de error en la ventana de salida.
        /// </summary>
        internal static string ERROR_EN_VENTANA_SALIDA {
            get {
                return ResourceManager.GetString("ERROR_EN_VENTANA_SALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revise la configuración de la opción con idioma origen {0} y destino {1}.
        /// </summary>
        internal static string ERROR_IDIOMA_ORIGEN_DESTINO_IGUALES_CONFIGURACION {
            get {
                return ResourceManager.GetString("ERROR_IDIOMA_ORIGEN_DESTINO_IGUALES_CONFIGURACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La palabra {0} no permite detectar el idioma origen, por favor configure este..
        /// </summary>
        internal static string ERROR_IDIOMA_ORIGEN_DESTINO_IGUALES_DETECTADO {
            get {
                return ResourceManager.GetString("ERROR_IDIOMA_ORIGEN_DESTINO_IGUALES_DETECTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La traducción ha finalizado.
        /// </summary>
        internal static string FIN {
            get {
                return ResourceManager.GetString("FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de I18N.
        /// </summary>
        internal static string ITEM_MENU__ACERCA_DE {
            get {
                return ResourceManager.GetString("ITEM_MENU__ACERCA_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar a idioma.
        /// </summary>
        internal static string ITEM_MENU__CAMBIAR_IDIOMA {
            get {
                return ResourceManager.GetString("ITEM_MENU__CAMBIAR_IDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traducir.
        /// </summary>
        internal static string ITEM_MENU__TRADUCIR {
            get {
                return ResourceManager.GetString("ITEM_MENU__TRADUCIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear opciones de traducción.
        /// </summary>
        internal static string ITEM_MENU_CREAR_OPCIONES {
            get {
                return ResourceManager.GetString("ITEM_MENU_CREAR_OPCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error pegado en el portapapeles.
        /// </summary>
        internal static string MSG__ERROR_PORTAPAPELES {
            get {
                return ResourceManager.GetString("MSG__ERROR_PORTAPAPELES", resourceCulture);
            }
        }
    }
}
