//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        internal static string COMPLEJIDAD_ALTA_LABEL {
            get {
                return ResourceManager.GetString("COMPLEJIDAD_ALTA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string COMPLEJIDAD_ALTA_VALOR {
            get {
                return ResourceManager.GetString("COMPLEJIDAD_ALTA_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja.
        /// </summary>
        internal static string COMPLEJIDAD_BAJA_LABEL {
            get {
                return ResourceManager.GetString("COMPLEJIDAD_BAJA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string COMPLEJIDAD_BAJA_VALOR {
            get {
                return ResourceManager.GetString("COMPLEJIDAD_BAJA_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string COMPLEJIDAD_MEDIA_LABEL {
            get {
                return ResourceManager.GetString("COMPLEJIDAD_MEDIA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string COMPLEJIDAD_MEDIA_VALOR {
            get {
                return ResourceManager.GetString("COMPLEJIDAD_MEDIA_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low,Medium,High.
        /// </summary>
        internal static string DIFICULTAD_ALTA_MEDIA_BAJA {
            get {
                return ResourceManager.GetString("DIFICULTAD_ALTA_MEDIA_BAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó.
        /// </summary>
        internal static string EJECUTOR_CREADO {
            get {
                return ResourceManager.GetString("EJECUTOR_CREADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se reemplazó al anónimo.
        /// </summary>
        internal static string EJECUTOR_REEMPLAZO_ANONIMO {
            get {
                return ResourceManager.GetString("EJECUTOR_REEMPLAZO_ANONIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando.
        /// </summary>
        internal static string ELIMINANDO {
            get {
                return ResourceManager.GetString("ELIMINANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error, el mensaje está en el portapapeles.
        /// </summary>
        internal static string ERROR_EN_PORTAPAPELES {
            get {
                return ResourceManager.GetString("ERROR_EN_PORTAPAPELES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculado.
        /// </summary>
        internal static string ESFUERZO_CALCULADO {
            get {
                return ResourceManager.GetString("ESFUERZO_CALCULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfuerzo.
        /// </summary>
        internal static string ESFUERZO_EDITOR_NAME {
            get {
                return ResourceManager.GetString("ESFUERZO_EDITOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfuerzo.
        /// </summary>
        internal static string ESFUERZO_ETIQUETA {
            get {
                return ResourceManager.GetString("ESFUERZO_ETIQUETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ESFUERZO_MANUAL {
            get {
                return ResourceManager.GetString("ESFUERZO_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos guardados.
        /// </summary>
        internal static string GUARDADO {
            get {
                return ResourceManager.GetString("GUARDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Save_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Save_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcular esfuerzo.
        /// </summary>
        internal static string MENU_ITEM_CALCULAR_ESFUERZO {
            get {
                return ResourceManager.GetString("MENU_ITEM_CALCULAR_ESFUERZO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo diario asignado para ejecutar la tarea.
        /// </summary>
        internal static string tooltip_asignado {
            get {
                return ResourceManager.GetString("tooltip_asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual que se ha completado de la tarea.
        /// </summary>
        internal static string tooltip_completado {
            get {
                return ResourceManager.GetString("tooltip_completado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo/esfuerzo que espera dedicar a la tarea.
        /// </summary>
        internal static string tooltip_esperado {
            get {
                return ResourceManager.GetString("tooltip_esperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo utilizado/invertido en la tarea.
        /// </summary>
        internal static string tooltip_utilizado {
            get {
                return ResourceManager.GetString("tooltip_utilizado", resourceCulture);
            }
        }
    }
}
