///////////////////////////////////////////////////////////
//  SecurityScheme.cs
//  Implementation of the Class SecurityScheme
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:52
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Una declaración de qué esquemas de seguridad se aplican para el API en su
/// conjunto. La lista de valores describe esquemas de seguridad alternativos que
/// pueden utilizarse (es decir, existe un OR lógico entre los requisitos de
/// seguridad). Las operaciones individuales pueden anular esta definición.
/// </summary>
public class SecurityScheme {

	public SecurityTypes type;
	/// <summary>
	/// Una breve descripción del esquema de seguridad.
	/// </summary>
	public string description;

	public SecurityScheme(){

	}

	~SecurityScheme(){

	}

}//end SecurityScheme