///////////////////////////////////////////////////////////
//  APIKeyInValues.cs
//  Implementation of the Enumeration APIKeyInValues
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:27
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum APIKeyInValues : int {

	query,
	header

}//end APIKeyInValues