///////////////////////////////////////////////////////////
//  Schemes.cs
//  Implementation of the Enumeration Schemes
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:47
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Schemes : int {

	http,
	https,
	ws,
	wss

}//end Schemes