///////////////////////////////////////////////////////////
//  Scopes.cs
//  Implementation of the Class Scopes
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:48
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace RestFul.modelo
{

    public class Scopes
    {

        /// <summary>
        /// Mapas entre un nombre de un ámbito a una breve descripción de él (como el valor
        /// de la propiedad).
        /// </summary>
        public string name;

        public Scopes()
        {

        }
    }
}