///////////////////////////////////////////////////////////
//  SecurityRequirement.cs
//  Implementation of the Class SecurityRequirement
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:51
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace RestFul.modelo
{

    /// <summary>
    /// Una declaración de qué esquemas de seguridad se aplican para el API en su
    /// conjunto. La lista de valores describe esquemas de seguridad alternativos que
    /// pueden utilizarse (es decir, existe un OR lógico entre los requisitos de
    /// seguridad). Las operaciones individuales pueden anular esta definición.
    /// </summary>
    public class SecurityRequirement
    {

        public SecurityScheme name;

        public SecurityRequirement()
        {

        }
    }
}