///////////////////////////////////////////////////////////
//  SecurityDefinition.cs
//  Implementation of the Class SecurityDefinition
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:50
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Definiciones de los esquemas de seguridad que se pueden utilizar a lo largo de
/// la especificación.
/// </summary>
public class SecurityDefinition {

	public SecurityDefinition(){

	}

	~SecurityDefinition(){

	}

}//end SecurityDefinition