///////////////////////////////////////////////////////////
//  SecurityTypes.cs
//  Implementation of the Enumeration SecurityTypes
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:53
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum SecurityTypes : int {

	basic,
	apiKey,
	oauth2

}//end SecurityTypes