///////////////////////////////////////////////////////////
//  Definition.cs
//  Implementation of the Class Definition
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:33
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Objeto para almacenar tipos de datos producidos y consumidos por operaciones.
/// </summary>
public class Definition {

	public Definition(){

	}

	~Definition(){

	}

}//end Definition