///////////////////////////////////////////////////////////
//  JsonSchema.cs
//  Implementation of the Class JsonSchema
//  Generated by Enterprise Architect
//  Created on:      30-jul.-2017 12:36:25
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Productividad.modelo {
	/// <summary>
	/// El Objeto Esquema permite la definición de tipos de datos de entrada y salida.
	/// Estos tipos pueden ser objetos, pero también primitivas y matrices. Este objeto
	/// se basa en el JSON Schema Specification Draft 4 y utiliza un subconjunto
	/// predefinido del mismo. En la parte superior de este subconjunto, hay
	/// extensiones proporcionadas por esta especificación para permitir una
	/// documentación más completa.
	/// 
	/// Se puede encontrar más información sobre las propiedades en JSON Schema Core y
	/// JSON Schema Validation. A menos que se indique lo contrario, las definiciones
	/// de propiedad siguen la especificación de JSON Schema como se hace referencia
	/// aquí.
	/// </summary>
	public class JsonSchema : JsonSchemaCommon {

        public Boolean required;
        public Nullable<int> minProperties = null;
        public Nullable<int> maxProperties = null;
        public string @ref = null;

		public JsonSchema(){
		}
	}
}