///////////////////////////////////////////////////////////
//  License.cs
//  Implementation of the Class License
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:36
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Objeto que contiene parámetros que se pueden utilizar en todas las operaciones.
/// Esta propiedad no define parámetros globales para todas las operaciones.
/// </summary>
public class License {

	/// <summary>
	/// El nombre de licencia utilizado para la API.
	/// </summary>
	public string name;
	/// <summary>
	/// Una URL de la licencia utilizada para la API. Debe estar en el formato de una
	/// URL.
	/// </summary>
	public string url;

	public License(){

	}

	~License(){

	}

}//end License