///////////////////////////////////////////////////////////
//  Oauth2.cs
//  Implementation of the Class Oauth2
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:37
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Productividad.modelo
{


    public class Oauth2 : SecurityScheme
    {

        public string authorizationUrl;
        public string tokenUrl;
        public Scopes scopes;

        public Oauth2()
        {

        }
    }
}