//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMN.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actualizado.
        /// </summary>
        public static string actualizado {
            get {
                return ResourceManager.GetString("actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tabla.
        /// </summary>
        public static string business_knowledge_sufijo {
            get {
                return ResourceManager.GetString("business_knowledge_sufijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a business_knowledge_sufijo.
        /// </summary>
        public static string business_knowledge_sufijo_key {
            get {
                return ResourceManager.GetString("business_knowledge_sufijo_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha copiado en el porta papeles.
        /// </summary>
        public static string copiado_portapapeles {
            get {
                return ResourceManager.GetString("copiado_portapapeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a creado.
        /// </summary>
        public static string creado {
            get {
                return ResourceManager.GetString("creado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string elegir_lenguaje_window_button_cancel_label {
            get {
                return ResourceManager.GetString("elegir_lenguaje_window_button_cancel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir el lenguaje.
        /// </summary>
        public static string elegir_lenguaje_window_title {
            get {
                return ResourceManager.GetString("elegir_lenguaje_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha {0} la enumeración.
        /// </summary>
        public static string enumeracion_ok {
            get {
                return ResourceManager.GetString("enumeracion_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La estrategia (aggregation) de conclusión no ha sido establecida.
        /// </summary>
        public static string error_aggregation {
            get {
                return ResourceManager.GetString("error_aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La completitud (completeness) de tabla no ha sido determinada.
        /// </summary>
        public static string error_completeness {
            get {
                return ResourceManager.GetString("error_completeness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las conclusiones no están completas.
        /// </summary>
        public static string error_conclusiones_incompletas {
            get {
                return ResourceManager.GetString("error_conclusiones_incompletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las condiciones no están completas.
        /// </summary>
        public static string error_condiciones_incompletas {
            get {
                return ResourceManager.GetString("error_condiciones_incompletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La estrategia (hit policy) de decisión no ha sido establecida.
        /// </summary>
        public static string error_hitPolicy {
            get {
                return ResourceManager.GetString("error_hitPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error, por favor consulte la salida del sistema.
        /// </summary>
        public static string error_indeterminado {
            get {
                return ResourceManager.GetString("error_indeterminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento {0} debe pertenecer a un DataContainer.
        /// </summary>
        public static string error_no_pertence_a_dataContainer {
            get {
                return ResourceManager.GetString("error_no_pertence_a_dataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las reglas no están completas.
        /// </summary>
        public static string error_reglas_incompletas {
            get {
                return ResourceManager.GetString("error_reglas_incompletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener la tabla de decisión del elemento.
        /// </summary>
        public static string error_tablaDecision_obtener {
            get {
                return ResourceManager.GetString("error_tablaDecision_obtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere de una tabla definida para el elemento.
        /// </summary>
        public static string error_tablaDecision_requerida {
            get {
                return ResourceManager.GetString("error_tablaDecision_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El elemento {0} no tiene definido el tipo de dato.
        /// </summary>
        public static string error_tipo__dato_no_definido {
            get {
                return ResourceManager.GetString("error_tipo__dato_no_definido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Add_Property_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Add_Property_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Add_Property_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Add_Property_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Copy_to_Clipboard_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Copy_to_Clipboard_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_JSON_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_JSON_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_JSON_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_JSON_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Play_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Play_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Plus_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Plus_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Plus_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Plus_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Save_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Save_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Sort_Down_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Sort_Down_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Source_Code_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Source_Code_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Source_Code_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Source_Code_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Trash_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Trash_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Trash_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Trash_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_XML_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_XML_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_XML_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_XML_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha instanciado {0}.
        /// </summary>
        public static string instanciado {
            get {
                return ResourceManager.GetString("instanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha instanciado  {0} desde {1}.
        /// </summary>
        public static string instanciado_desde {
            get {
                return ResourceManager.GetString("instanciado_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar variable.
        /// </summary>
        public static string ITEM_MENU__AGREGAR_VARIABLE {
            get {
                return ResourceManager.GetString("ITEM_MENU__AGREGAR_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear enumeraciones desde variable.
        /// </summary>
        public static string ITEM_MENU__CREAR_ENUMERACION {
            get {
                return ResourceManager.GetString("ITEM_MENU__CREAR_ENUMERACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir editor de variable.
        /// </summary>
        public static string ITEM_MENU__EDITOR_VARIABLE {
            get {
                return ResourceManager.GetString("ITEM_MENU__EDITOR_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar el alias.
        /// </summary>
        public static string ITEM_MENU__ENUM2CSV__ALIAS {
            get {
                return ResourceManager.GetString("ITEM_MENU__ENUM2CSV__ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar el nombre.
        /// </summary>
        public static string ITEM_MENU__ENUM2CSV__NAME {
            get {
                return ResourceManager.GetString("ITEM_MENU__ENUM2CSV__NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enumeración al portapapeles como CSV.
        /// </summary>
        public static string ITEM_MENU__ENUM2CSV_MENU {
            get {
                return ResourceManager.GetString("ITEM_MENU__ENUM2CSV_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar código fuente.
        /// </summary>
        public static string ITEM_MENU__GENERAR_CODIGO {
            get {
                return ResourceManager.GetString("ITEM_MENU__GENERAR_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar .dmn.
        /// </summary>
        public static string ITEM_MENU__GENERAR_DMN_XML {
            get {
                return ResourceManager.GetString("ITEM_MENU__GENERAR_DMN_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        public static string ITEM_MENU__GENERAR_MENU {
            get {
                return ResourceManager.GetString("ITEM_MENU__GENERAR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción no implementada.
        /// </summary>
        public static string no_implementada {
            get {
                return ResourceManager.GetString("no_implementada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No implementada desde el menú aún.
        /// </summary>
        public static string no_implementada_desde_menu {
            get {
                return ResourceManager.GetString("no_implementada_desde_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar ....
        /// </summary>
        public static string seleccionar {
            get {
                return ResourceManager.GetString("seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado una variable anónima.
        /// </summary>
        public static string variable_creada {
            get {
                return ResourceManager.GetString("variable_creada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre atributo.
        /// </summary>
        public static string variable_editor_label_attributeName {
            get {
                return ResourceManager.GetString("variable_editor_label_attributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etiqueta.
        /// </summary>
        public static string variable_editor_label_businessName {
            get {
                return ResourceManager.GetString("variable_editor_label_businessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        public static string variable_editor_label_default {
            get {
                return ResourceManager.GetString("variable_editor_label_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato.
        /// </summary>
        public static string variable_editor_label_format {
            get {
                return ResourceManager.GetString("variable_editor_label_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string variable_editor_label_type {
            get {
                return ResourceManager.GetString("variable_editor_label_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar variable.
        /// </summary>
        public static string variable_editor_tooltip_agregar {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear enumeración.
        /// </summary>
        public static string variable_editor_tooltip_crear_enumeracion {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_crear_enumeracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar variable.
        /// </summary>
        public static string variable_editor_tooltip_eliminar {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar código fuente.
        /// </summary>
        public static string variable_editor_tooltip_generar_codigo {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_generar_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar .dmn.
        /// </summary>
        public static string variable_editor_tooltip_generar_dmn {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_generar_dmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar JSON.
        /// </summary>
        public static string variable_editor_tooltip_generar_json {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_generar_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string variable_editor_tooltip_guardar {
            get {
                return ResourceManager.GetString("variable_editor_tooltip_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La variable no está en uso o, si ha modificado algún dato debe abrir la tabla para que se refresque.
        /// </summary>
        public static string variable_noUsada {
            get {
                return ResourceManager.GetString("variable_noUsada", resourceCulture);
            }
        }
    }
}
