///////////////////////////////////////////////////////////
//  ParameterNotInBody.cs
//  Implementation of the Class ParameterNotInBody
//  Generated by Enterprise Architect
//  Created on:      30-jul.-2017 12:20:09
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace Productividad.modelo
{
	public class ParameterNotInBody : JsonSchemaCommon
    {
        /// <summary>
        /// Establece la capacidad de pasar los parámetros de valores vacíos. Esto es
        /// válido sólo para los parámetros query o formData y le permite enviar un
        /// parámetro con sólo un nombre o un valor vacío. El valor predeterminado es false.
        /// 
        /// </summary>
        public Nullable<Boolean> allowEmptyValue = null;
        /// <summary>
        /// Describe el tipo de elementos de la matriz.
        /// </summary>
        public List<Item> items = new List<Item>();

		public ParameterNotInBody(){

		}

	}

}