//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDGBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDGBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build info.
        /// </summary>
        internal static string build_info {
            get {
                return ResourceManager.GetString("build_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar MDG.
        /// </summary>
        internal static string editor_configuracion_boton_buildMDG {
            get {
                return ResourceManager.GetString("editor_configuracion_boton_buildMDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incrementar Major.
        /// </summary>
        internal static string editor_configuracion_boton_incrementMajor {
            get {
                return ResourceManager.GetString("editor_configuracion_boton_incrementMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incrementar Minor.
        /// </summary>
        internal static string editor_configuracion_boton_incrementMinor {
            get {
                return ResourceManager.GetString("editor_configuracion_boton_incrementMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usar versionado semántico.
        /// </summary>
        internal static string editor_configuracion_usar_versionado_semántico {
            get {
                return ResourceManager.GetString("editor_configuracion_usar_versionado_semántico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_construction_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_construction_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_construction_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_construction_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_plus_math_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_plus_math_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Plus_Math_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Plus_Math_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_refresh_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_refresh_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Save_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Save_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar _metatype.
        /// </summary>
        internal static string ITEM_MENU__ADD_METATYPE {
            get {
                return ResourceManager.GetString("ITEM_MENU__ADD_METATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar.
        /// </summary>
        internal static string ITEM_MENU__CONFIGURAR {
            get {
                return ResourceManager.GetString("ITEM_MENU__CONFIGURAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor de Quicklinker.
        /// </summary>
        internal static string ITEM_MENU__EDITOR_QUICKLINKER {
            get {
                return ResourceManager.GetString("ITEM_MENU__EDITOR_QUICKLINKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Datos de Referencia.
        /// </summary>
        internal static string ITEM_MENU__EXPORT_REFERENCE_DATA {
            get {
                return ResourceManager.GetString("ITEM_MENU__EXPORT_REFERENCE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar MDG.
        /// </summary>
        internal static string ITEM_MENU__GENERAR {
            get {
                return ResourceManager.GetString("ITEM_MENU__GENERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Entregable.
        /// </summary>
        internal static string ITEM_MENU__GENERAR_ENTREGABLE {
            get {
                return ResourceManager.GetString("ITEM_MENU__GENERAR_ENTREGABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Quicklinker.
        /// </summary>
        internal static string ITEM_MENU__GENERAR_QUICKLINKER {
            get {
                return ResourceManager.GetString("ITEM_MENU__GENERAR_QUICKLINKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar datos desde MTS.
        /// </summary>
        internal static string ITEM_MENU__IMPORTAR_MTS {
            get {
                return ResourceManager.GetString("ITEM_MENU__IMPORTAR_MTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinronizar Estereotipos.
        /// </summary>
        internal static string ITEM_MENU__SINCRONIZAR_ESTEREOTIPOS {
            get {
                return ResourceManager.GetString("ITEM_MENU__SINCRONIZAR_ESTEREOTIPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha generado el MDG.
        /// </summary>
        internal static string MDG_BUILD_OK {
            get {
                return ResourceManager.GetString("MDG_BUILD_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargado.
        /// </summary>
        internal static string MESSAGE_CONIFGURACION_RELOAD {
            get {
                return ResourceManager.GetString("MESSAGE_CONIFGURACION_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado.
        /// </summary>
        internal static string MESSAGE_CONIFGURACION_SAVED {
            get {
                return ResourceManager.GetString("MESSAGE_CONIFGURACION_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre MDG.
        /// </summary>
        internal static string nombre_MDG {
            get {
                return ResourceManager.GetString("nombre_MDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre MDG.
        /// </summary>
        internal static string nuevo_nombre_MDG {
            get {
                return ResourceManager.GetString("nuevo_nombre_MDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión MDG.
        /// </summary>
        internal static string version_MDG {
            get {
                return ResourceManager.GetString("version_MDG", resourceCulture);
            }
        }
    }
}
