///////////////////////////////////////////////////////////
//  Contact.cs
//  Implementation of the Class Contact
//  Generated by Enterprise Architect
//  Created on:      28-jul.-2017 13:59:30
//  Original author: Edgardo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Objeto que contiene parámetros que se pueden utilizar en todas las operaciones.
/// Esta propiedad no define parámetros globales para todas las operaciones.
/// </summary>
public class Contact {

	/// <summary>
	/// El nombre de identificación de la persona / organización de contacto.
	/// </summary>
	public string name;
	/// <summary>
	/// La URL que apunta a la información de contacto. Debe estar en el formato de una
	/// URL.
	/// </summary>
	public string url;
	/// <summary>
	/// La dirección de correo electrónico de la persona / organización de contacto.
	/// Debe estar en el formato de una dirección de correo electrónico.
	/// </summary>
	public string email;

	public Contact(){

	}

	~Contact(){

	}

}//end Contact